In [2]:
import numpy as np
from scipy.sparse import csr_matrix

In [3]:
vector_row=np.array([1,2,3])
vector_column=np.array([[1],[2],[3]])
print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


In [4]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [5]:
matrix=np.array([[0,0],[0,1],[3,0]])
print(matrix)

print()
matrix_sparse=csr_matrix(matrix)
print(matrix_sparse)

[[0 0]
 [0 1]
 [3 0]]

  (1, 1)	1
  (2, 0)	3


In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
#Mean
print(np.mean(matrix))
#Standard Dev.
print(np.std(matrix))
#Variance
print(np.var(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
2.581988897471611
6.666666666666667


In [7]:
print(matrix)
print(matrix.reshape(9,1))
print()
print(matrix.flatten())
print()
print(matrix.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

[1 2 3 4 5 6 7 8 9]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


<h2>Eigen Values

Eigenvectors are widely used in Machine Learning libraries. Intutively given a linear transformation represented by a matrix,A, eigenvectors are vectors that when that transformation is applied, change only in scale(not direction).More formally

Av=Kv

In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print()

# Calculate the Eigenvalues and Eigenvectors of that Matrix
eigenvalues ,eigenvectors=np.linalg.eig(matrix)
print(eigenvalues)
print()
print(eigenvectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [9]:
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.dot(a,b)
print(c)

20


In [10]:
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])
#Add the 2 Matrices
print(np.add(matrix_1,matrix_2))
#Subtraction
print(np.subtract(matrix_1,matrix_2))

#Multiplication(Element wise, not Dot Product)
print(matrix_1*matrix_2)

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [16]:
print(matrix)
print(f"length of array is {len(matrix[0])}")
print(f"array subset: {matrix[1:2]}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
length of array is 3
array subset: [[4 5 6]]


In [17]:
arr=np.array([2,1,4,5,3])
print(np.sort(arr))

[1 2 3 4 5]


In [ ]:
import pandas