In [24]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn import preprocessing
from pickle import dump
import seaborn as sns
import pickle

In [25]:
df=pd.read_csv("CleanedData.csv") #reading the processed data
df.head()

area_type  bath  balcony  price  total_sqft  size         prft  \
0          3   3.0      2.0  150.0      1672.0   2.0  8971.291866   
1          0   3.0      3.0  149.0      1750.0   3.0  8514.285714   
2          3   3.0      2.0  150.0      1750.0   3.0  8571.428571   
3          3   2.0      3.0   44.0      1250.0   3.0  3520.000000   
4          3   2.0      2.0   40.0      1250.0   2.0  3200.000000   

   availability  location_Whitefield  location_Sarjapur  Road  ...  \
0            12                    0                        0  ...   
1            12                    0                        0  ...   
2            12                    0                        0  ...   
3             9                    0                        0  ...   
4            12                    0                        0  ...   

   location_Bommasandra  location_Vijayanagar  location_Channasandra  \
0                     0                     0                      0   
1                     0                     0                      0   
2                     0                     0                      0   
3                     0                     0                      0   
4                     0                     0                      0   

   location_Choodasandra  location_Mahadevpura  location_Old Airport Road  \
0                      0                     0                          0   
1                      0                     0                          0   
2                      0                     0                          0   
3                      0                     0                          0   
4                      0                     0                          0   

   location_Kanakapura  location_Ambedkar Nagar  location_Anekal  \
0                    0                        0                0   
1                    0                        0                0   
2                    0                        0                0   
3                    0                        0                0   
4                    0                        0                0   

   location_Kothannur  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 94 columns]

# Splitting the data into test and train

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X=df.drop("price",axis=1)
y=df["price"]
print("Shape of X",X.shape)
print("Shape of y",y.shape)

('Shape of X', (6926, 93))
('Shape of y', (6926,))


In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=51)
print("Shape of X_train",X_train.shape)
print("Shape of X_test",X_test.shape)
print("Shape of y_train",y_train.shape)
print("Shape of y_test",y_test.shape)

('Shape of X_train', (5540, 93))
('Shape of X_test', (1386, 93))
('Shape of y_train', (5540,))
('Shape of y_test', (1386,))


# Feature Scaling

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
sc=StandardScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)

/home/prabhat/.local/lib/python2.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until
/home/prabhat/.local/lib/python2.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


# Model training

<h2> Linear Regression

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

lr=LinearRegression()
ls=Lasso()
rg=Ridge()

In [32]:
#Function to check the mean squared error
def rmse(y_test,y_pred):
    return np.sqrt(mean_squared_error(y_test,y_pred))

In [33]:
#Linear Regression
lr.fit(X_train,y_train)
lr_score=lr.score(X_test,y_test)
lr_rmse=rmse(y_test,lr.predict(X_test))
print("Linear Regression "+str(lr_score)+","+str(lr_rmse))

Linear Regression 0.932202091741231,18.70715639713961


In [34]:
#Lasso
ls.fit(X_train,y_train)
ls_score=ls.score(X_test,y_test)
ls_rmse=rmse(y_test,ls.predict(X_test))
print("Lasso "+str(ls_score)+","+str(ls_rmse))

Lasso 0.9327438475890113,18.63226442107239


In [35]:
#Ridge
rg.fit(X_train,y_train)
rg_score=rg.score(X_test,y_test)
rg_rmse=rmse(y_test,rg.predict(X_test))
print("Ridge "+str(rg_score)+","+str(rg_rmse))

Ridge 0.9322172654826217,18.705062870622196


In [36]:
#Support Vector Machine
from sklearn.svm import SVR
svr=SVR()
svr.fit(X_train,y_train)
svr_score=svr.score(X_test,y_test)
svr_rmse=rmse(y_test,svr.predict(X_test))
print("Support Vector Machine "+str(svr_score)+","+str(svr_rmse))

Support Vector Machine 0.4357593210850411,53.96744111136593


In [37]:
#Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(X_train,y_train)
rf_score=rf.score(X_test,y_test)
rf_rmse=rmse(y_test,rf.predict(X_test))
print("Random Forest Regressor "+str(rf_score)+","+str(rf_rmse))

Random Forest Regressor 0.8823280252167427,24.645415850262285


In [38]:
store=pd.DataFrame([{"Model":'Linear','Score':lr_score,'RMSE':lr_rmse},
{"Model":'Lasso','Score':ls_score,'RMSE':ls_rmse},
{"Model":'Ridge','Score':rg_score,'RMSE':rg_rmse}])

In [39]:
store.to_csv("Loc15TotSqft350.csv")
store

Model       RMSE     Score
0  Linear  18.707156  0.932202
1   Lasso  18.632264  0.932744
2   Ridge  18.705063  0.932217

In [40]:
st=pd.read_csv("Loc20TotSqft350.csv")
st

Unnamed: 0   Model       RMSE     Score
0           0  Linear  18.707156  0.932202
1           1   Lasso  18.632264  0.932744
2           2   Ridge  18.705063  0.932217

In [45]:
X.head()

area_type  bath  balcony  total_sqft  size         prft  availability  \
0          3   3.0      2.0      1672.0   2.0  8971.291866            12   
1          0   3.0      3.0      1750.0   3.0  8514.285714            12   
2          3   3.0      2.0      1750.0   3.0  8571.428571            12   
3          3   2.0      3.0      1250.0   3.0  3520.000000             9   
4          3   2.0      2.0      1250.0   2.0  3200.000000            12   

   location_Whitefield  location_Sarjapur  Road  location_Electronic City  \
0                    0                        0                         0   
1                    0                        0                         0   
2                    0                        0                         0   
3                    0                        0                         0   
4                    0                        0                         0   

   ...  location_Bommasandra  location_Vijayanagar  location_Channasandra  \
0  ...                     0                     0                      0   
1  ...                     0                     0                      0   
2  ...                     0                     0                      0   
3  ...                     0                     0                      0   
4  ...                     0                     0                      0   

   location_Choodasandra  location_Mahadevpura  location_Old Airport Road  \
0                      0                     0                          0   
1                      0                     0                          0   
2                      0                     0                          0   
3                      0                     0                          0   
4                      0                     0                          0   

   location_Kanakapura  location_Ambedkar Nagar  location_Anekal  \
0                    0                        0                0   
1                    0                        0                0   
2                    0                        0                0   
3                    0                        0                0   
4                    0                        0                0   

   location_Kothannur  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 93 columns]

In [49]:
from sklearn import preprocessing
import pickle
lb = preprocessing.LabelEncoder()


In [50]:
lb=preprocessing.LabelEncoder()

In [51]:
bo=pd.read_csv("label.csv")

In [52]:
bo["availability"]=lb.fit_transform(bo["availability"])

In [56]:
f=pd.read_csv("pred.csv")
f.head()

area_type  bath  balcony  price  total_sqft  size         prft  \
0          3     2        2    150        1850     3  8971.291866   

   availability  location_Whitefield  location_Sarjapur  Road  ...  \
0             3                    1                        0  ...   

   location_Bommasandra  location_Vijayanagar  location_Channasandra  \
0                     0                     0                      0   

   location_Choodasandra  location_Mahadevpura  location_Old Airport Road  \
0                      0                     0                          0   

   location_Kanakapura  location_Ambedkar Nagar  location_Anekal  \
0                    0                        0                0   

   location_Kothannur  
0                   0  

[1 rows x 94 columns]

In [57]:
f=f.drop("price",axis=1)

In [64]:
sc=StandardScaler()
sc.fit(f)
f=sc.transform(f)


In [65]:
rg.predict(f)


array([89.0038213])

In [66]:
ls.predict(f)

array([89.0038213])

In [67]:
rf.predict(f)

array([84.522])

In [68]:
lr.predict(f)

array([89.0038213])

# The final price is 89 